#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# This run file contains all of the common functional tests.  When
# adding a new test consider also adding it to the sanity.run file
# if the new test runs to completion in only a few seconds.
#
# Approximate run time: 4-5 hours
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 300
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
outputdir = /var/tmp/test_results
tags = ['functional']

[tests/functional/removal]
pre =
tests = ['removal_all_vdev', 'removal_cancel', 'removal_check_space',
    'removal_condense_export', 'removal_multiple_indirection',
    'removal_nopwrite', 'removal_remap_deadlists',
    'removal_resume_export', 'removal_sanity', 'removal_with_add',
    'removal_with_create_fs', 'removal_with_dedup',
    'removal_with_errors', 'removal_with_export',
    'removal_with_ganging', 'removal_with_faulted',
    'removal_with_remove', 'removal_with_scrub', 'removal_with_send',
    'removal_with_send_recv', 'removal_with_snapshot',
    'removal_with_write', 'removal_with_zdb', 'remove_expanded',
    'remove_mirror', 'remove_mirror_sanity', 'remove_raidz',
    'remove_indirect', 'remove_attach_mirror']
tags = ['functional', 'removal']

