name: zfs-qemu

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      fedora_kernel_ver:
        type: string
        required: false
        default: ""
        description: "(optional) Experimental kernel version to install on Fedora (like '6.14' or '6.13.3-0.rc3')"
      specific_os:
        type: string
        required: false
        default: ""
        description: "(optional) Only run on this specific OS (like 'fedora44' or 'alpine3-24')"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-config:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.repository != 'openzfs/zfs'
    runs-on: ubuntu-24.04

    steps:
      - name: Try to get api
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2026-03-10" https://api.github.com/repos/openzfs/zfs/actions/artifacts/9537868682/zip
          ls -l
